version: '3.8'

services:
  api:
    build: api/
    depends_on:
      - redis
    ports:
      - "3000:3000"
  crawler:
    build: crawler/
    depends_on:
      - redis
  redis:
    image: redis:latest
    container_name: redis_container
    volumes:
      - ./data/redis:/data
